### ISSUE TITLE
Tern plugin for JOII

### ISSUE THREAD

**Issue by angelozerr** [haroldiedema/joii#14]
I create this issue because you have posted at http://stackoverflow.com/questions/24092184/eclipse-plugin-development-modify-the-outline-of-javascript-editor

IMHO, I think you should write a http://ternjs.net plugin because : 

 * ternjs is very powerful
 * they exists a lot of tern plugin like angular, jQuery, dojo, yui, etc
 * a tern plugin is written is JavaSCript and can be used with several editor like Atom, Vim, Emacs, Eclipse and web browser (see demo at http://ternjs.net/doc/demo.html)

If you are interested, I could assist you to create this tern plugin.

**Comment by haroldiedema** [comment]
Oh, that's really neat! Since I don't use Eclipse anymore, I wonder if this would also work with Phpstorm...

The question on stackoverflow was created for an old version of JOII where code-completion was really bad. Ever since JOII 3.x was released, this wasn't much of a problem anymore. Although the difference in property visibility is still a problem :')

Unfortunately my schedule is really full right now and for months to come. So if you're up for it, feel free to make this plugin happen. I'd happily integrate it into this repo or link to a repo of yours, whatever suits you best.

**Comment by angelozerr** [comment]
> Oh, that's really neat! Since I don't use Eclipse anymore, I wonder if this would also work with Phpstorm..

No -(, Phpstorm doesn't the capability to use tern, but it will possible with tern.java https://github.com/angelozerr/tern.java if JetBrains guys wish to integrate it.

> Unfortunately my schedule is really full right now and for months to come. So if you're up for it, feel free to make this plugin happen

Ok, I'm very busy too, but when I will ahve time, I will try it.

**Comment by haroldiedema** [comment]
Closing this issue for now as there is no priority / demand for this.
