### ISSUE TITLE
Getting infinite recursion when using Reflection

### ISSUE THREAD

**Issue by tnielsen** [haroldiedema/joii#15]
I ran into an issue, reproduced with the following code:

```javascript
var A = JOII.ClassBuilder({
    'public function f1': function() {},
    'public function f2': function() {
        this.f1();
    }
});
var B = Class({'extends': A}, {
    'public function f3': function() {
        this.f2();
    },
});
var b = new B();
b.f3();

var reflector = new JOII.Reflection.Class(B);
```

I think this was introduced with the fix for Issue #11.  What happens is that when creating the Reflection on Class B, it goes into an infinite recursion loop.  If I remove the call to f3, then the reflector line works fine.

**Comment by haroldiedema** [comment]
Alright. That's a bug.

Using Reflection on a class should not care _at all_ what you do inside your methods. I'm not actively developing on JOII anymore, since ECMAScript6 is litterally around the corner. Feel free to send a PR if you find a fix for this without breaking other parts.

To play it safe, I would advice to somehow keep track of "loaded" classes to prevent circular references.
