### ISSUE TITLE
Unexpected function being called when using inheritance

### ISSUE THREAD

**Issue by tnielsen** [haroldiedema/joii#16]
I ran into an odd issue while using JOII, and I've reproduced it with the following code:

```javascript
var A = JOII.ClassBuilder({
    'public function f1': function() {},
    'public function type': function() {
        return 'A';
    },
    'public function f2': function() {
        this.f1();
        return this.type();
    }
});
var B = Class({'extends': A}, {
    'public function type': function() {
        return 'B';
    }
});
var C = Class({'extends': B}, {
});

var b = new B();
var c = new C();

assert.equal(b.f2(), 'B')
assert.equal(c.f2(), 'B')  // I expected it to return 'B', but it actually returns 'A'
```

I would expect `c` to call `B.f2()`, but it appears to be calling `A.f2()`.  If I remove the call to `b.f2()`, then `c.f2()` works as I expect.  Also, if I call `c.f2()`, before `b.f2()`, then it works as I expect (even if I later call `c.f2()` afterward).

I think this is a bug, but I could be doing something wrong.

**Comment by haroldiedema** [comment]
Hmm, funny you've stumbled across this. I've been aware of this issue since the very first versions of JOII. Not because it's a bug, but it's actually how the inheritance system works. All JOII does is copy the prototype of parents onto its children while keeping track of the inheritance 'tree' using a special propertly on the class and instance definitions.

I'm sorry to say that this isn't something you can fix without breaking other parts of the library. If you do find a way to do it, feel free to send a PR.
