### ISSUE TITLE
struct support

### ISSUE THREAD

**Issue by cjmanca** [haroldiedema/joii#23]
I often have data objects which need to be JSON serialized to send back and forth between the server. Currently, I can't use joii classes for these, since their members are hidden behind accessor methods. They can't be serialized easily, so I've been forced to use standard javascript objects for these.

It would be nice to be able to have a serializable data structure, which still allows for strong typing when adding as a class member variable.

Eg:

```
var MyStruct = Struct('MyStruct', {
    name: 'a name'
});

var MyClass = Class('MyClass', {
    'public MyStruct data': new MyStruct(); // strongly typed
});

var mc = new MyClass();
console.log(mc.getData()); // should print out {name: 'a name'}
```

**Comment by cjmanca** [comment]
The other option would be to implement a "serialize/deserialize" method in the existing joii Class, and possibly have an extra meta data tag on each variable to specify why is/isn't serialized?

**Comment by haroldiedema** [comment]
Standard JSON wouldn't work here if you also wish to be able to deserialize the data back into JOII objects, since the type-data is lost.

I've looked at this in the past, but wasn't able to come up with a robust solution. If you wish to re-instantiate objects with the data, then you'd need to know where the classes are located in the scope. For example, the serialized data would contain the name of a class and the data. However, said class may or may not be in the global scope at any time, making the functionality completely unreliable.

You could create a serialize/deserialize function, but for deserializing strings, you'd still have the same problem with scoping, since some child nodes may not have their classes available in the scope.


Also, this is quite dangerous since the state of the `MyStruct` instance is now shared over all instances of `MyClass`. You should instantiate `MyStruct` in de `constructor` of `MyClass`.
```
var MyClass = Class('MyClass', {
    'public immutable MyStruct data': null,

    construct: function () {
        this.data = new MyStruct(); // strongly typed
    }
});
```

**Comment by cjmanca** [comment]
Interesting. I'm used to other languages, where in-line initializing will run the initialization code for each new object. Good to know that it runs only once in this case.

As for serializing/deserializing - I'd be ok with including a class name as an extra variable. Also, usually when you're deserializing a well known structure, you know what you're deserializing, so it's easy to require the appropriate file ahead of time.

All that aside though - what about a "light" serialize/deserialize which doesn't need to include what class it was? You'd need to call a static deserialize method on the original class though.

**Comment by cjmanca** [comment]
Here's a thought though - in general when you're writing a class, you need all of the types of it's member variables in scope. That means that if you force them to deserialize by calling a static deserialize method on the original class (passing in the serialized data), then all of it's sub-classes would be in scope for that class. 

You could even enforce this by making sure all those member variable classes are in scope at the time of class creation.

**Comment by cjmanca** [comment]
#24
